# Generated by Django 6.0 on 2026-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categoria_producto_creado_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='novedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
